# Base Image - comes with Python + pip
# This file uses pip3 explicitly to install packages
FROM python:3.11-slim

WORKDIR /app

# Install OS dependencies
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*


# Copy app files & install Python dependencies
COPY app.py embed.py k8s.txt ./
RUN pip3 install fastapi uvicorn chromadb ollama

# pre-compute embeddings
RUN python3 embed.py

# Start API
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
